//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Account
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataserverPortalUsersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataserverPortalUsersEntities object using the connection string found in the 'DataserverPortalUsersEntities' section of the application configuration file.
        /// </summary>
        public DataserverPortalUsersEntities() : base("name=DataserverPortalUsersEntities", "DataserverPortalUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataserverPortalUsersEntities object.
        /// </summary>
        public DataserverPortalUsersEntities(string connectionString) : base(connectionString, "DataserverPortalUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataserverPortalUsersEntities object.
        /// </summary>
        public DataserverPortalUsersEntities(EntityConnection connection) : base(connection, "DataserverPortalUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataserverPortalUser> DataserverPortalUsers
        {
            get
            {
                if ((_DataserverPortalUsers == null))
                {
                    _DataserverPortalUsers = base.CreateObjectSet<DataserverPortalUser>("DataserverPortalUsers");
                }
                return _DataserverPortalUsers;
            }
        }
        private ObjectSet<DataserverPortalUser> _DataserverPortalUsers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataserverPortalUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataserverPortalUsers(DataserverPortalUser dataserverPortalUser)
        {
            base.AddObject("DataserverPortalUsers", dataserverPortalUser);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataserverPortalUsersEntitiesModel", Name="DataserverPortalUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataserverPortalUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataserverPortalUser object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ssoCode">Initial value of the SsoCode property.</param>
        public static DataserverPortalUser CreateDataserverPortalUser(global::System.Guid id, global::System.Guid ssoCode)
        {
            DataserverPortalUser dataserverPortalUser = new DataserverPortalUser();
            dataserverPortalUser.Id = id;
            dataserverPortalUser.SsoCode = ssoCode;
            return dataserverPortalUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SsoCode
        {
            get
            {
                return _SsoCode;
            }
            set
            {
                OnSsoCodeChanging(value);
                ReportPropertyChanging("SsoCode");
                _SsoCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SsoCode");
                OnSsoCodeChanged();
            }
        }
        private global::System.Guid _SsoCode;
        partial void OnSsoCodeChanging(global::System.Guid value);
        partial void OnSsoCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PortalUri
        {
            get
            {
                return _PortalUri;
            }
            set
            {
                OnPortalUriChanging(value);
                ReportPropertyChanging("PortalUri");
                _PortalUri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PortalUri");
                OnPortalUriChanged();
            }
        }
        private global::System.String _PortalUri;
        partial void OnPortalUriChanging(global::System.String value);
        partial void OnPortalUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PortalName
        {
            get
            {
                return _PortalName;
            }
            set
            {
                OnPortalNameChanging(value);
                ReportPropertyChanging("PortalName");
                _PortalName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PortalName");
                OnPortalNameChanged();
            }
        }
        private global::System.String _PortalName;
        partial void OnPortalNameChanging(global::System.String value);
        partial void OnPortalNameChanged();

        #endregion
    
    }

    #endregion
    
}
