<?xml version="1.0" encoding="utf-8"?><Database Name="AgapeConnect" Class="gmaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=AgapeConnect;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SiteSqlServer" Provider="System.Data.SqlClient" />
  <Table Name="dbo.gma_Servers" Member="gma_Servers">
    <Type Name="gma_Server">
      <Column Name="gmaServerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="displayName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="rootUrl" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="serviceUrl" Storage="_serviceURL" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="addedByUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>