<?xml version="1.0" encoding="utf-8"?><Database Name="AgapeConnect" Class="BudgetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=AgapeConnect;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SiteSqlServer" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AP_Budget_Project" Member="AP_Budget_Projects">
    <Type Name="AP_Budget_Project">
      <Column Name="BudProjId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RC" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="PortalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FiscalYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectManager" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="AP_Budget_Project_AP_Budget_Transaction" Member="AP_Budget_Transactions" ThisKey="BudProjId" OtherKey="ProjectId" Type="AP_Budget_Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.AP_Budget_Transactions" Member="AP_Budget_Transactions">
    <Type Name="AP_Budget_Transaction">
      <Column Name="BudgetTransactionId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="RC" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="P1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P3" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P4" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P5" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P6" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P7" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P8" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P9" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P10" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P11" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P12" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="FiscalYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DateSubmitted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateApproved" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateProcessed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PortalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AP_Budget_Project_AP_Budget_Transaction" Member="AP_Budget_Project" ThisKey="ProjectId" OtherKey="BudProjId" Type="AP_Budget_Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AP_Budget_Summary" Member="AP_Budget_Summaries">
    <Type Name="AP_Budget_Summary">
      <Column Name="BudgetSummaryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="RC" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="P1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P3" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P4" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P5" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P6" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P7" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P8" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P9" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P10" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P11" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P12" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="FiscalYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Changed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Portalid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Error" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="nvarchar(500)" CanBeNull="true" />
      <Association Name="AP_StaffBroker_CostCenter_AP_Budget_Summary" Member="AP_StaffBroker_CostCenter" ThisKey="Portalid,RC" OtherKey="PortalId,CostCentreCode" Type="AP_StaffBroker_CostCenter" IsForeignKey="true" />
      <Association Name="AP_StaffBroker_AccountCode_AP_Budget_Summary" Member="AP_StaffBroker_AccountCode" ThisKey="Portalid,Account" OtherKey="PortalId,AccountCode" Type="AP_StaffBroker_AccountCode" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AP_StaffBroker_AccountCodes" Member="AP_StaffBroker_AccountCodes">
    <Type Name="AP_StaffBroker_AccountCode">
      <Column Name="AccountCodeId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountCode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="AccountCodeName" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="AccountCodeType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PortalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AP_StaffBroker_AccountCode_AP_Budget_Summary" Member="AP_Budget_Summaries" ThisKey="PortalId,AccountCode" OtherKey="Portalid,Account" Type="AP_Budget_Summary" />
    </Type>
  </Table>
  <Table Name="dbo.AP_StaffBroker_CostCenters" Member="AP_StaffBroker_CostCenters">
    <Type Name="AP_StaffBroker_CostCenter">
      <Column Name="CostCentreId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CostCentreCode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="CostCentreName" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="PortalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="AP_StaffBroker_CostCenter_AP_Budget_Summary" Member="AP_Budget_Summaries" ThisKey="PortalId,CostCentreCode" OtherKey="Portalid,RC" Type="AP_Budget_Summary" />
    </Type>
  </Table>
  <Table Name="dbo.AP_Budget_Summary" Member="AP_Budget_Summary1s">
    <Type Name="AP_Budget_Summary1">
      <Column Name="BudgetSummaryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="RC" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="P1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P3" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P4" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P5" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P6" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P7" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P8" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P9" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P10" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P11" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="P12" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="FiscalYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Changed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Portalid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Error" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>