#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffRmb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AgapeConnect")]
	public partial class StaffRmbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAP_Staff_RmbLineType(AP_Staff_RmbLineType instance);
    partial void UpdateAP_Staff_RmbLineType(AP_Staff_RmbLineType instance);
    partial void DeleteAP_Staff_RmbLineType(AP_Staff_RmbLineType instance);
    partial void InsertAP_StaffRmb_PortalLineType(AP_StaffRmb_PortalLineType instance);
    partial void UpdateAP_StaffRmb_PortalLineType(AP_StaffRmb_PortalLineType instance);
    partial void DeleteAP_StaffRmb_PortalLineType(AP_StaffRmb_PortalLineType instance);
    partial void InsertAP_StaffBroker_Department(AP_StaffBroker_Department instance);
    partial void UpdateAP_StaffBroker_Department(AP_StaffBroker_Department instance);
    partial void DeleteAP_StaffBroker_Department(AP_StaffBroker_Department instance);
    partial void InsertAP_StaffBroker_CostCenter(AP_StaffBroker_CostCenter instance);
    partial void UpdateAP_StaffBroker_CostCenter(AP_StaffBroker_CostCenter instance);
    partial void DeleteAP_StaffBroker_CostCenter(AP_StaffBroker_CostCenter instance);
    partial void InsertAP_StaffBroker_AccountCode(AP_StaffBroker_AccountCode instance);
    partial void UpdateAP_StaffBroker_AccountCode(AP_StaffBroker_AccountCode instance);
    partial void DeleteAP_StaffBroker_AccountCode(AP_StaffBroker_AccountCode instance);
    partial void InsertAP_Staff_Rmb(AP_Staff_Rmb instance);
    partial void UpdateAP_Staff_Rmb(AP_Staff_Rmb instance);
    partial void DeleteAP_Staff_Rmb(AP_Staff_Rmb instance);
    partial void InsertAP_Staff_AdvanceRequest(AP_Staff_AdvanceRequest instance);
    partial void UpdateAP_Staff_AdvanceRequest(AP_Staff_AdvanceRequest instance);
    partial void DeleteAP_Staff_AdvanceRequest(AP_Staff_AdvanceRequest instance);
    partial void InsertAP_Staff_Rmb_PerDeimMuliType(AP_Staff_Rmb_PerDeimMuliType instance);
    partial void UpdateAP_Staff_Rmb_PerDeimMuliType(AP_Staff_Rmb_PerDeimMuliType instance);
    partial void DeleteAP_Staff_Rmb_PerDeimMuliType(AP_Staff_Rmb_PerDeimMuliType instance);
    partial void InsertAP_Staff_RmbLine(AP_Staff_RmbLine instance);
    partial void UpdateAP_Staff_RmbLine(AP_Staff_RmbLine instance);
    partial void DeleteAP_Staff_RmbLine(AP_Staff_RmbLine instance);
    #endregion
		
		public StaffRmbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StaffRmbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StaffRmbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StaffRmbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StaffRmbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AP_Staff_RmbLineType> AP_Staff_RmbLineTypes
		{
			get
			{
				return this.GetTable<AP_Staff_RmbLineType>();
			}
		}
		
		public System.Data.Linq.Table<AP_StaffRmb_PortalLineType> AP_StaffRmb_PortalLineTypes
		{
			get
			{
				return this.GetTable<AP_StaffRmb_PortalLineType>();
			}
		}
		
		public System.Data.Linq.Table<AP_StaffBroker_Department> AP_StaffBroker_Departments
		{
			get
			{
				return this.GetTable<AP_StaffBroker_Department>();
			}
		}
		
		public System.Data.Linq.Table<AP_StaffBroker_CostCenter> AP_StaffBroker_CostCenters
		{
			get
			{
				return this.GetTable<AP_StaffBroker_CostCenter>();
			}
		}
		
		public System.Data.Linq.Table<AP_StaffBroker_AccountCode> AP_StaffBroker_AccountCodes
		{
			get
			{
				return this.GetTable<AP_StaffBroker_AccountCode>();
			}
		}
		
		public System.Data.Linq.Table<AP_Staff_Rmb> AP_Staff_Rmbs
		{
			get
			{
				return this.GetTable<AP_Staff_Rmb>();
			}
		}
		
		public System.Data.Linq.Table<AP_Staff_AdvanceRequest> AP_Staff_AdvanceRequests
		{
			get
			{
				return this.GetTable<AP_Staff_AdvanceRequest>();
			}
		}
		
		public System.Data.Linq.Table<AP_Staff_Rmb_PerDeimMuliType> AP_Staff_Rmb_PerDeimMuliTypes
		{
			get
			{
				return this.GetTable<AP_Staff_Rmb_PerDeimMuliType>();
			}
		}
		
		public System.Data.Linq.Table<AP_Staff_RmbLine> AP_Staff_RmbLines
		{
			get
			{
				return this.GetTable<AP_Staff_RmbLine>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_Staff_RmbLineType")]
	public partial class AP_Staff_RmbLineType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _LineTypeId;
		
		private string _TypeName;
		
		private string _ControlPath;
		
		private string _SpareField1;
		
		private string _SpareField2;
		
		private EntitySet<AP_StaffRmb_PortalLineType> _AP_StaffRmb_PortalLineTypes;
		
		private EntitySet<AP_Staff_RmbLine> _AP_Staff_RmbLines;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLineTypeIdChanging(short value);
    partial void OnLineTypeIdChanged();
    partial void OnTypeNameChanging(string value);
    partial void OnTypeNameChanged();
    partial void OnControlPathChanging(string value);
    partial void OnControlPathChanged();
    partial void OnSpareField1Changing(string value);
    partial void OnSpareField1Changed();
    partial void OnSpareField2Changing(string value);
    partial void OnSpareField2Changed();
    #endregion
		
		public AP_Staff_RmbLineType()
		{
			this._AP_StaffRmb_PortalLineTypes = new EntitySet<AP_StaffRmb_PortalLineType>(new Action<AP_StaffRmb_PortalLineType>(this.attach_AP_StaffRmb_PortalLineTypes), new Action<AP_StaffRmb_PortalLineType>(this.detach_AP_StaffRmb_PortalLineTypes));
			this._AP_Staff_RmbLines = new EntitySet<AP_Staff_RmbLine>(new Action<AP_Staff_RmbLine>(this.attach_AP_Staff_RmbLines), new Action<AP_Staff_RmbLine>(this.detach_AP_Staff_RmbLines));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineTypeId", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short LineTypeId
		{
			get
			{
				return this._LineTypeId;
			}
			set
			{
				if ((this._LineTypeId != value))
				{
					this.OnLineTypeIdChanging(value);
					this.SendPropertyChanging();
					this._LineTypeId = value;
					this.SendPropertyChanged("LineTypeId");
					this.OnLineTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this.OnTypeNameChanging(value);
					this.SendPropertyChanging();
					this._TypeName = value;
					this.SendPropertyChanged("TypeName");
					this.OnTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ControlPath", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ControlPath
		{
			get
			{
				return this._ControlPath;
			}
			set
			{
				if ((this._ControlPath != value))
				{
					this.OnControlPathChanging(value);
					this.SendPropertyChanging();
					this._ControlPath = value;
					this.SendPropertyChanged("ControlPath");
					this.OnControlPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField1", DbType="NVarChar(50)")]
		public string SpareField1
		{
			get
			{
				return this._SpareField1;
			}
			set
			{
				if ((this._SpareField1 != value))
				{
					this.OnSpareField1Changing(value);
					this.SendPropertyChanging();
					this._SpareField1 = value;
					this.SendPropertyChanged("SpareField1");
					this.OnSpareField1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField2", DbType="NVarChar(50)")]
		public string SpareField2
		{
			get
			{
				return this._SpareField2;
			}
			set
			{
				if ((this._SpareField2 != value))
				{
					this.OnSpareField2Changing(value);
					this.SendPropertyChanging();
					this._SpareField2 = value;
					this.SendPropertyChanged("SpareField2");
					this.OnSpareField2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AP_Staff_RmbLineType_AP_StaffRmb_PortalLineType", Storage="_AP_StaffRmb_PortalLineTypes", ThisKey="LineTypeId", OtherKey="LineTypeId")]
		public EntitySet<AP_StaffRmb_PortalLineType> AP_StaffRmb_PortalLineTypes
		{
			get
			{
				return this._AP_StaffRmb_PortalLineTypes;
			}
			set
			{
				this._AP_StaffRmb_PortalLineTypes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AP_Staff_RmbLineType_AP_Staff_RmbLine", Storage="_AP_Staff_RmbLines", ThisKey="LineTypeId", OtherKey="LineType")]
		public EntitySet<AP_Staff_RmbLine> AP_Staff_RmbLines
		{
			get
			{
				return this._AP_Staff_RmbLines;
			}
			set
			{
				this._AP_Staff_RmbLines.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AP_StaffRmb_PortalLineTypes(AP_StaffRmb_PortalLineType entity)
		{
			this.SendPropertyChanging();
			entity.AP_Staff_RmbLineType = this;
		}
		
		private void detach_AP_StaffRmb_PortalLineTypes(AP_StaffRmb_PortalLineType entity)
		{
			this.SendPropertyChanging();
			entity.AP_Staff_RmbLineType = null;
		}
		
		private void attach_AP_Staff_RmbLines(AP_Staff_RmbLine entity)
		{
			this.SendPropertyChanging();
			entity.AP_Staff_RmbLineType = this;
		}
		
		private void detach_AP_Staff_RmbLines(AP_Staff_RmbLine entity)
		{
			this.SendPropertyChanging();
			entity.AP_Staff_RmbLineType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_StaffRmb_PortalLineType")]
	public partial class AP_StaffRmb_PortalLineType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PortalLineTypeId;
		
		private short _LineTypeId;
		
		private int _PortalId;
		
		private string _LocalName;
		
		private string _PCode;
		
		private string _DCode;
		
		private System.Nullable<short> _ViewOrder;
		
		private EntityRef<AP_Staff_RmbLineType> _AP_Staff_RmbLineType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPortalLineTypeIdChanging(int value);
    partial void OnPortalLineTypeIdChanged();
    partial void OnLineTypeIdChanging(short value);
    partial void OnLineTypeIdChanged();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    partial void OnLocalNameChanging(string value);
    partial void OnLocalNameChanged();
    partial void OnPCodeChanging(string value);
    partial void OnPCodeChanged();
    partial void OnDCodeChanging(string value);
    partial void OnDCodeChanged();
    partial void OnViewOrderChanging(System.Nullable<short> value);
    partial void OnViewOrderChanged();
    #endregion
		
		public AP_StaffRmb_PortalLineType()
		{
			this._AP_Staff_RmbLineType = default(EntityRef<AP_Staff_RmbLineType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalLineTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PortalLineTypeId
		{
			get
			{
				return this._PortalLineTypeId;
			}
			set
			{
				if ((this._PortalLineTypeId != value))
				{
					this.OnPortalLineTypeIdChanging(value);
					this.SendPropertyChanging();
					this._PortalLineTypeId = value;
					this.SendPropertyChanged("PortalLineTypeId");
					this.OnPortalLineTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineTypeId", DbType="SmallInt NOT NULL")]
		public short LineTypeId
		{
			get
			{
				return this._LineTypeId;
			}
			set
			{
				if ((this._LineTypeId != value))
				{
					if (this._AP_Staff_RmbLineType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLineTypeIdChanging(value);
					this.SendPropertyChanging();
					this._LineTypeId = value;
					this.SendPropertyChanged("LineTypeId");
					this.OnLineTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL")]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalName", DbType="NVarChar(50)")]
		public string LocalName
		{
			get
			{
				return this._LocalName;
			}
			set
			{
				if ((this._LocalName != value))
				{
					this.OnLocalNameChanging(value);
					this.SendPropertyChanging();
					this._LocalName = value;
					this.SendPropertyChanged("LocalName");
					this.OnLocalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCode", DbType="NVarChar(20)")]
		public string PCode
		{
			get
			{
				return this._PCode;
			}
			set
			{
				if ((this._PCode != value))
				{
					this.OnPCodeChanging(value);
					this.SendPropertyChanging();
					this._PCode = value;
					this.SendPropertyChanged("PCode");
					this.OnPCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCode", DbType="NVarChar(20)")]
		public string DCode
		{
			get
			{
				return this._DCode;
			}
			set
			{
				if ((this._DCode != value))
				{
					this.OnDCodeChanging(value);
					this.SendPropertyChanging();
					this._DCode = value;
					this.SendPropertyChanged("DCode");
					this.OnDCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewOrder", DbType="SmallInt")]
		public System.Nullable<short> ViewOrder
		{
			get
			{
				return this._ViewOrder;
			}
			set
			{
				if ((this._ViewOrder != value))
				{
					this.OnViewOrderChanging(value);
					this.SendPropertyChanging();
					this._ViewOrder = value;
					this.SendPropertyChanged("ViewOrder");
					this.OnViewOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AP_Staff_RmbLineType_AP_StaffRmb_PortalLineType", Storage="_AP_Staff_RmbLineType", ThisKey="LineTypeId", OtherKey="LineTypeId", IsForeignKey=true)]
		public AP_Staff_RmbLineType AP_Staff_RmbLineType
		{
			get
			{
				return this._AP_Staff_RmbLineType.Entity;
			}
			set
			{
				AP_Staff_RmbLineType previousValue = this._AP_Staff_RmbLineType.Entity;
				if (((previousValue != value) 
							|| (this._AP_Staff_RmbLineType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AP_Staff_RmbLineType.Entity = null;
						previousValue.AP_StaffRmb_PortalLineTypes.Remove(this);
					}
					this._AP_Staff_RmbLineType.Entity = value;
					if ((value != null))
					{
						value.AP_StaffRmb_PortalLineTypes.Add(this);
						this._LineTypeId = value.LineTypeId;
					}
					else
					{
						this._LineTypeId = default(short);
					}
					this.SendPropertyChanged("AP_Staff_RmbLineType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_StaffBroker_Departments")]
	public partial class AP_StaffBroker_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CostCenterId;
		
		private string _Name;
		
		private string _CostCentre;
		
		private System.Nullable<int> _CostCentreManager;
		
		private System.Nullable<int> _CostCentreDelegate;
		
		private bool _CanRmb;
		
		private bool _CanCharge;
		
		private bool _CanGiveTo;
		
		private string _GivingText;
		
		private string _GivingShortcut;
		
		private System.Nullable<int> _PortalId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCostCenterIdChanging(int value);
    partial void OnCostCenterIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostCentreChanging(string value);
    partial void OnCostCentreChanged();
    partial void OnCostCentreManagerChanging(System.Nullable<int> value);
    partial void OnCostCentreManagerChanged();
    partial void OnCostCentreDelegateChanging(System.Nullable<int> value);
    partial void OnCostCentreDelegateChanged();
    partial void OnCanRmbChanging(bool value);
    partial void OnCanRmbChanged();
    partial void OnCanChargeChanging(bool value);
    partial void OnCanChargeChanged();
    partial void OnCanGiveToChanging(bool value);
    partial void OnCanGiveToChanged();
    partial void OnGivingTextChanging(string value);
    partial void OnGivingTextChanged();
    partial void OnGivingShortcutChanging(string value);
    partial void OnGivingShortcutChanged();
    partial void OnPortalIdChanging(System.Nullable<int> value);
    partial void OnPortalIdChanged();
    #endregion
		
		public AP_StaffBroker_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCenterId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CostCenterId
		{
			get
			{
				return this._CostCenterId;
			}
			set
			{
				if ((this._CostCenterId != value))
				{
					this.OnCostCenterIdChanging(value);
					this.SendPropertyChanging();
					this._CostCenterId = value;
					this.SendPropertyChanged("CostCenterId");
					this.OnCostCenterIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCentre", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CostCentre
		{
			get
			{
				return this._CostCentre;
			}
			set
			{
				if ((this._CostCentre != value))
				{
					this.OnCostCentreChanging(value);
					this.SendPropertyChanging();
					this._CostCentre = value;
					this.SendPropertyChanged("CostCentre");
					this.OnCostCentreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCentreManager", DbType="Int")]
		public System.Nullable<int> CostCentreManager
		{
			get
			{
				return this._CostCentreManager;
			}
			set
			{
				if ((this._CostCentreManager != value))
				{
					this.OnCostCentreManagerChanging(value);
					this.SendPropertyChanging();
					this._CostCentreManager = value;
					this.SendPropertyChanged("CostCentreManager");
					this.OnCostCentreManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCentreDelegate", DbType="Int")]
		public System.Nullable<int> CostCentreDelegate
		{
			get
			{
				return this._CostCentreDelegate;
			}
			set
			{
				if ((this._CostCentreDelegate != value))
				{
					this.OnCostCentreDelegateChanging(value);
					this.SendPropertyChanging();
					this._CostCentreDelegate = value;
					this.SendPropertyChanged("CostCentreDelegate");
					this.OnCostCentreDelegateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanRmb", DbType="Bit NOT NULL")]
		public bool CanRmb
		{
			get
			{
				return this._CanRmb;
			}
			set
			{
				if ((this._CanRmb != value))
				{
					this.OnCanRmbChanging(value);
					this.SendPropertyChanging();
					this._CanRmb = value;
					this.SendPropertyChanged("CanRmb");
					this.OnCanRmbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanCharge", DbType="Bit NOT NULL")]
		public bool CanCharge
		{
			get
			{
				return this._CanCharge;
			}
			set
			{
				if ((this._CanCharge != value))
				{
					this.OnCanChargeChanging(value);
					this.SendPropertyChanging();
					this._CanCharge = value;
					this.SendPropertyChanged("CanCharge");
					this.OnCanChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanGiveTo", DbType="Bit NOT NULL")]
		public bool CanGiveTo
		{
			get
			{
				return this._CanGiveTo;
			}
			set
			{
				if ((this._CanGiveTo != value))
				{
					this.OnCanGiveToChanging(value);
					this.SendPropertyChanging();
					this._CanGiveTo = value;
					this.SendPropertyChanged("CanGiveTo");
					this.OnCanGiveToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivingText", DbType="NVarChar(MAX)")]
		public string GivingText
		{
			get
			{
				return this._GivingText;
			}
			set
			{
				if ((this._GivingText != value))
				{
					this.OnGivingTextChanging(value);
					this.SendPropertyChanging();
					this._GivingText = value;
					this.SendPropertyChanged("GivingText");
					this.OnGivingTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivingShortcut", DbType="NVarChar(50)")]
		public string GivingShortcut
		{
			get
			{
				return this._GivingShortcut;
			}
			set
			{
				if ((this._GivingShortcut != value))
				{
					this.OnGivingShortcutChanging(value);
					this.SendPropertyChanging();
					this._GivingShortcut = value;
					this.SendPropertyChanged("GivingShortcut");
					this.OnGivingShortcutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int")]
		public System.Nullable<int> PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_StaffBroker_CostCenters")]
	public partial class AP_StaffBroker_CostCenter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CostCentreId;
		
		private string _CostCentreCode;
		
		private string _CostCentreName;
		
		private int _PortalId;
		
		private System.Nullable<byte> _Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCostCentreIdChanging(long value);
    partial void OnCostCentreIdChanged();
    partial void OnCostCentreCodeChanging(string value);
    partial void OnCostCentreCodeChanged();
    partial void OnCostCentreNameChanging(string value);
    partial void OnCostCentreNameChanged();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    partial void OnTypeChanging(System.Nullable<byte> value);
    partial void OnTypeChanged();
    #endregion
		
		public AP_StaffBroker_CostCenter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCentreId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long CostCentreId
		{
			get
			{
				return this._CostCentreId;
			}
			set
			{
				if ((this._CostCentreId != value))
				{
					this.OnCostCentreIdChanging(value);
					this.SendPropertyChanging();
					this._CostCentreId = value;
					this.SendPropertyChanged("CostCentreId");
					this.OnCostCentreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCentreCode", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string CostCentreCode
		{
			get
			{
				return this._CostCentreCode;
			}
			set
			{
				if ((this._CostCentreCode != value))
				{
					this.OnCostCentreCodeChanging(value);
					this.SendPropertyChanging();
					this._CostCentreCode = value;
					this.SendPropertyChanged("CostCentreCode");
					this.OnCostCentreCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCentreName", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CostCentreName
		{
			get
			{
				return this._CostCentreName;
			}
			set
			{
				if ((this._CostCentreName != value))
				{
					this.OnCostCentreNameChanging(value);
					this.SendPropertyChanging();
					this._CostCentreName = value;
					this.SendPropertyChanged("CostCentreName");
					this.OnCostCentreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL")]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="tinyint")]
		public System.Nullable<byte> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_StaffBroker_AccountCodes")]
	public partial class AP_StaffBroker_AccountCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _AccountCodeId;
		
		private string _AccountCode;
		
		private string _AccountCodeName;
		
		private System.Nullable<byte> _AccountCodeType;
		
		private int _PortalId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountCodeIdChanging(long value);
    partial void OnAccountCodeIdChanged();
    partial void OnAccountCodeChanging(string value);
    partial void OnAccountCodeChanged();
    partial void OnAccountCodeNameChanging(string value);
    partial void OnAccountCodeNameChanged();
    partial void OnAccountCodeTypeChanging(System.Nullable<byte> value);
    partial void OnAccountCodeTypeChanged();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    #endregion
		
		public AP_StaffBroker_AccountCode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCodeId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long AccountCodeId
		{
			get
			{
				return this._AccountCodeId;
			}
			set
			{
				if ((this._AccountCodeId != value))
				{
					this.OnAccountCodeIdChanging(value);
					this.SendPropertyChanging();
					this._AccountCodeId = value;
					this.SendPropertyChanged("AccountCodeId");
					this.OnAccountCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this.OnAccountCodeChanging(value);
					this.SendPropertyChanging();
					this._AccountCode = value;
					this.SendPropertyChanged("AccountCode");
					this.OnAccountCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCodeName", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string AccountCodeName
		{
			get
			{
				return this._AccountCodeName;
			}
			set
			{
				if ((this._AccountCodeName != value))
				{
					this.OnAccountCodeNameChanging(value);
					this.SendPropertyChanging();
					this._AccountCodeName = value;
					this.SendPropertyChanged("AccountCodeName");
					this.OnAccountCodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCodeType", DbType="TinyInt")]
		public System.Nullable<byte> AccountCodeType
		{
			get
			{
				return this._AccountCodeType;
			}
			set
			{
				if ((this._AccountCodeType != value))
				{
					this.OnAccountCodeTypeChanging(value);
					this.SendPropertyChanging();
					this._AccountCodeType = value;
					this.SendPropertyChanged("AccountCodeType");
					this.OnAccountCodeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL")]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_Staff_Rmb")]
	public partial class AP_Staff_Rmb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _RMBNo;
		
		private int _UserId;
		
		private string _CostCenter;
		
		private string _UserRef;
		
		private System.Nullable<System.DateTime> _RmbDate;
		
		private int _Status;
		
		private string _UserComment;
		
		private string _ApprComment;
		
		private string _AcctComment;
		
		private System.Nullable<int> _ApprUserId;
		
		private bool _Locked;
		
		private int _PortalId;
		
		private System.Nullable<System.DateTime> _ApprDate;
		
		private System.Nullable<System.DateTime> _ProcDate;
		
		private System.Nullable<byte> _Period;
		
		private System.Nullable<short> _Year;
		
		private string _SupplierCode;
		
		private bool _EmailSent;
		
		private bool _Changed;
		
		private decimal _AdvanceRequest;
		
		private bool _Department;
		
		private string _SpareField1;
		
		private string _SpareField2;
		
		private string _SpareField3;
		
		private string _SpareField4;
		
		private string _SpareField5;
		
		private int _RID;
		
		private bool _Error;
		
		private string _ErrorMessage;
		
		private System.Nullable<System.DateTime> _DownloadDate;
		
		private string _DownloadMode;
		
		private System.Nullable<bool> _MoreInfoRequested;
		
		private System.Nullable<int> _ProcUserId;
		
		private EntitySet<AP_Staff_RmbLine> _AP_Staff_RmbLines;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRMBNoChanging(long value);
    partial void OnRMBNoChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnCostCenterChanging(string value);
    partial void OnCostCenterChanged();
    partial void OnUserRefChanging(string value);
    partial void OnUserRefChanged();
    partial void OnRmbDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRmbDateChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnUserCommentChanging(string value);
    partial void OnUserCommentChanged();
    partial void OnApprCommentChanging(string value);
    partial void OnApprCommentChanged();
    partial void OnAcctCommentChanging(string value);
    partial void OnAcctCommentChanged();
    partial void OnApprUserIdChanging(System.Nullable<int> value);
    partial void OnApprUserIdChanged();
    partial void OnLockedChanging(bool value);
    partial void OnLockedChanged();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    partial void OnApprDateChanging(System.Nullable<System.DateTime> value);
    partial void OnApprDateChanged();
    partial void OnProcDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProcDateChanged();
    partial void OnPeriodChanging(System.Nullable<byte> value);
    partial void OnPeriodChanged();
    partial void OnYearChanging(System.Nullable<short> value);
    partial void OnYearChanged();
    partial void OnSupplierCodeChanging(string value);
    partial void OnSupplierCodeChanged();
    partial void OnEmailSentChanging(bool value);
    partial void OnEmailSentChanged();
    partial void OnChangedChanging(bool value);
    partial void OnChangedChanged();
    partial void OnAdvanceRequestChanging(decimal value);
    partial void OnAdvanceRequestChanged();
    partial void OnDepartmentChanging(bool value);
    partial void OnDepartmentChanged();
    partial void OnSpareField1Changing(string value);
    partial void OnSpareField1Changed();
    partial void OnSpareField2Changing(string value);
    partial void OnSpareField2Changed();
    partial void OnSpareField3Changing(string value);
    partial void OnSpareField3Changed();
    partial void OnSpareField4Changing(string value);
    partial void OnSpareField4Changed();
    partial void OnSpareField5Changing(string value);
    partial void OnSpareField5Changed();
    partial void OnRIDChanging(int value);
    partial void OnRIDChanged();
    partial void OnErrorChanging(bool value);
    partial void OnErrorChanged();
    partial void OnErrorMessageChanging(string value);
    partial void OnErrorMessageChanged();
    partial void OnDownloadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDownloadDateChanged();
    partial void OnDownloadModeChanging(string value);
    partial void OnDownloadModeChanged();
    partial void OnMoreInfoRequestedChanging(System.Nullable<bool> value);
    partial void OnMoreInfoRequestedChanged();
    partial void OnProcUserIdChanging(System.Nullable<int> value);
    partial void OnProcUserIdChanged();
    #endregion
		
		public AP_Staff_Rmb()
		{
			this._AP_Staff_RmbLines = new EntitySet<AP_Staff_RmbLine>(new Action<AP_Staff_RmbLine>(this.attach_AP_Staff_RmbLines), new Action<AP_Staff_RmbLine>(this.detach_AP_Staff_RmbLines));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMBNo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long RMBNo
		{
			get
			{
				return this._RMBNo;
			}
			set
			{
				if ((this._RMBNo != value))
				{
					this.OnRMBNoChanging(value);
					this.SendPropertyChanging();
					this._RMBNo = value;
					this.SendPropertyChanged("RMBNo");
					this.OnRMBNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCenter", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CostCenter
		{
			get
			{
				return this._CostCenter;
			}
			set
			{
				if ((this._CostCenter != value))
				{
					this.OnCostCenterChanging(value);
					this.SendPropertyChanging();
					this._CostCenter = value;
					this.SendPropertyChanged("CostCenter");
					this.OnCostCenterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRef", DbType="NVarChar(100)")]
		public string UserRef
		{
			get
			{
				return this._UserRef;
			}
			set
			{
				if ((this._UserRef != value))
				{
					this.OnUserRefChanging(value);
					this.SendPropertyChanging();
					this._UserRef = value;
					this.SendPropertyChanged("UserRef");
					this.OnUserRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RmbDate", DbType="Date")]
		public System.Nullable<System.DateTime> RmbDate
		{
			get
			{
				return this._RmbDate;
			}
			set
			{
				if ((this._RmbDate != value))
				{
					this.OnRmbDateChanging(value);
					this.SendPropertyChanging();
					this._RmbDate = value;
					this.SendPropertyChanged("RmbDate");
					this.OnRmbDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserComment", DbType="NVarChar(MAX)")]
		public string UserComment
		{
			get
			{
				return this._UserComment;
			}
			set
			{
				if ((this._UserComment != value))
				{
					this.OnUserCommentChanging(value);
					this.SendPropertyChanging();
					this._UserComment = value;
					this.SendPropertyChanged("UserComment");
					this.OnUserCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprComment", DbType="NVarChar(MAX)")]
		public string ApprComment
		{
			get
			{
				return this._ApprComment;
			}
			set
			{
				if ((this._ApprComment != value))
				{
					this.OnApprCommentChanging(value);
					this.SendPropertyChanging();
					this._ApprComment = value;
					this.SendPropertyChanged("ApprComment");
					this.OnApprCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcctComment", DbType="NVarChar(MAX)")]
		public string AcctComment
		{
			get
			{
				return this._AcctComment;
			}
			set
			{
				if ((this._AcctComment != value))
				{
					this.OnAcctCommentChanging(value);
					this.SendPropertyChanging();
					this._AcctComment = value;
					this.SendPropertyChanged("AcctComment");
					this.OnAcctCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprUserId", DbType="Int")]
		public System.Nullable<int> ApprUserId
		{
			get
			{
				return this._ApprUserId;
			}
			set
			{
				if ((this._ApprUserId != value))
				{
					this.OnApprUserIdChanging(value);
					this.SendPropertyChanging();
					this._ApprUserId = value;
					this.SendPropertyChanged("ApprUserId");
					this.OnApprUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Locked", DbType="Bit NOT NULL")]
		public bool Locked
		{
			get
			{
				return this._Locked;
			}
			set
			{
				if ((this._Locked != value))
				{
					this.OnLockedChanging(value);
					this.SendPropertyChanging();
					this._Locked = value;
					this.SendPropertyChanged("Locked");
					this.OnLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL")]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprDate", DbType="Date")]
		public System.Nullable<System.DateTime> ApprDate
		{
			get
			{
				return this._ApprDate;
			}
			set
			{
				if ((this._ApprDate != value))
				{
					this.OnApprDateChanging(value);
					this.SendPropertyChanging();
					this._ApprDate = value;
					this.SendPropertyChanged("ApprDate");
					this.OnApprDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcDate", DbType="Date")]
		public System.Nullable<System.DateTime> ProcDate
		{
			get
			{
				return this._ProcDate;
			}
			set
			{
				if ((this._ProcDate != value))
				{
					this.OnProcDateChanging(value);
					this.SendPropertyChanging();
					this._ProcDate = value;
					this.SendPropertyChanged("ProcDate");
					this.OnProcDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="TinyInt")]
		public System.Nullable<byte> Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this.OnPeriodChanging(value);
					this.SendPropertyChanging();
					this._Period = value;
					this.SendPropertyChanged("Period");
					this.OnPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="SmallInt")]
		public System.Nullable<short> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierCode", DbType="VarChar(8)")]
		public string SupplierCode
		{
			get
			{
				return this._SupplierCode;
			}
			set
			{
				if ((this._SupplierCode != value))
				{
					this.OnSupplierCodeChanging(value);
					this.SendPropertyChanging();
					this._SupplierCode = value;
					this.SendPropertyChanged("SupplierCode");
					this.OnSupplierCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSent", DbType="Bit NOT NULL")]
		public bool EmailSent
		{
			get
			{
				return this._EmailSent;
			}
			set
			{
				if ((this._EmailSent != value))
				{
					this.OnEmailSentChanging(value);
					this.SendPropertyChanging();
					this._EmailSent = value;
					this.SendPropertyChanged("EmailSent");
					this.OnEmailSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Changed", DbType="Bit NOT NULL")]
		public bool Changed
		{
			get
			{
				return this._Changed;
			}
			set
			{
				if ((this._Changed != value))
				{
					this.OnChangedChanging(value);
					this.SendPropertyChanging();
					this._Changed = value;
					this.SendPropertyChanged("Changed");
					this.OnChangedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceRequest", DbType="Money NOT NULL")]
		public decimal AdvanceRequest
		{
			get
			{
				return this._AdvanceRequest;
			}
			set
			{
				if ((this._AdvanceRequest != value))
				{
					this.OnAdvanceRequestChanging(value);
					this.SendPropertyChanging();
					this._AdvanceRequest = value;
					this.SendPropertyChanged("AdvanceRequest");
					this.OnAdvanceRequestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Bit NOT NULL")]
		public bool Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField1", DbType="NVarChar(50)")]
		public string SpareField1
		{
			get
			{
				return this._SpareField1;
			}
			set
			{
				if ((this._SpareField1 != value))
				{
					this.OnSpareField1Changing(value);
					this.SendPropertyChanging();
					this._SpareField1 = value;
					this.SendPropertyChanged("SpareField1");
					this.OnSpareField1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField2", DbType="NVarChar(50)")]
		public string SpareField2
		{
			get
			{
				return this._SpareField2;
			}
			set
			{
				if ((this._SpareField2 != value))
				{
					this.OnSpareField2Changing(value);
					this.SendPropertyChanging();
					this._SpareField2 = value;
					this.SendPropertyChanged("SpareField2");
					this.OnSpareField2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField3", DbType="NVarChar(50)")]
		public string SpareField3
		{
			get
			{
				return this._SpareField3;
			}
			set
			{
				if ((this._SpareField3 != value))
				{
					this.OnSpareField3Changing(value);
					this.SendPropertyChanging();
					this._SpareField3 = value;
					this.SendPropertyChanged("SpareField3");
					this.OnSpareField3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField4", DbType="NVarChar(50)")]
		public string SpareField4
		{
			get
			{
				return this._SpareField4;
			}
			set
			{
				if ((this._SpareField4 != value))
				{
					this.OnSpareField4Changing(value);
					this.SendPropertyChanging();
					this._SpareField4 = value;
					this.SendPropertyChanged("SpareField4");
					this.OnSpareField4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField5", DbType="NVarChar(50)")]
		public string SpareField5
		{
			get
			{
				return this._SpareField5;
			}
			set
			{
				if ((this._SpareField5 != value))
				{
					this.OnSpareField5Changing(value);
					this.SendPropertyChanging();
					this._SpareField5 = value;
					this.SendPropertyChanged("SpareField5");
					this.OnSpareField5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", DbType="Int NOT NULL")]
		public int RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					this.OnRIDChanging(value);
					this.SendPropertyChanging();
					this._RID = value;
					this.SendPropertyChanged("RID");
					this.OnRIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Bit NOT NULL")]
		public bool Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(MAX)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this.OnErrorMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessage = value;
					this.SendPropertyChanged("ErrorMessage");
					this.OnErrorMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownloadDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DownloadDate
		{
			get
			{
				return this._DownloadDate;
			}
			set
			{
				if ((this._DownloadDate != value))
				{
					this.OnDownloadDateChanging(value);
					this.SendPropertyChanging();
					this._DownloadDate = value;
					this.SendPropertyChanged("DownloadDate");
					this.OnDownloadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownloadMode", DbType="NVarChar(20)")]
		public string DownloadMode
		{
			get
			{
				return this._DownloadMode;
			}
			set
			{
				if ((this._DownloadMode != value))
				{
					this.OnDownloadModeChanging(value);
					this.SendPropertyChanging();
					this._DownloadMode = value;
					this.SendPropertyChanged("DownloadMode");
					this.OnDownloadModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreInfoRequested", DbType="bit")]
		public System.Nullable<bool> MoreInfoRequested
		{
			get
			{
				return this._MoreInfoRequested;
			}
			set
			{
				if ((this._MoreInfoRequested != value))
				{
					this.OnMoreInfoRequestedChanging(value);
					this.SendPropertyChanging();
					this._MoreInfoRequested = value;
					this.SendPropertyChanged("MoreInfoRequested");
					this.OnMoreInfoRequestedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcUserId", DbType="Int")]
		public System.Nullable<int> ProcUserId
		{
			get
			{
				return this._ProcUserId;
			}
			set
			{
				if ((this._ProcUserId != value))
				{
					this.OnProcUserIdChanging(value);
					this.SendPropertyChanging();
					this._ProcUserId = value;
					this.SendPropertyChanged("ProcUserId");
					this.OnProcUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AP_Staff_Rmb_AP_Staff_RmbLine", Storage="_AP_Staff_RmbLines", ThisKey="RMBNo", OtherKey="RmbNo")]
		public EntitySet<AP_Staff_RmbLine> AP_Staff_RmbLines
		{
			get
			{
				return this._AP_Staff_RmbLines;
			}
			set
			{
				this._AP_Staff_RmbLines.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AP_Staff_RmbLines(AP_Staff_RmbLine entity)
		{
			this.SendPropertyChanging();
			entity.AP_Staff_Rmb = this;
		}
		
		private void detach_AP_Staff_RmbLines(AP_Staff_RmbLine entity)
		{
			this.SendPropertyChanging();
			entity.AP_Staff_Rmb = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_Staff_AdvanceRequest")]
	public partial class AP_Staff_AdvanceRequest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdvanceId;
		
		private System.Nullable<int> _LocalAdvanceId;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<short> _RequestStatus;
		
		private System.Nullable<decimal> _RequestAmount;
		
		private string _RequestText;
		
		private System.Nullable<System.DateTime> _RequestDate;
		
		private System.Nullable<int> _ApproverId;
		
		private System.Nullable<System.DateTime> _ApprovedDate;
		
		private System.Nullable<System.DateTime> _ProcessedDate;
		
		private System.Nullable<byte> _Period;
		
		private System.Nullable<short> _Year;
		
		private bool _Error;
		
		private string _ErrorMessage;
		
		private int _PortalId;
		
		private string _OrigCurrency;
		
		private System.Nullable<decimal> _OrigCurrencyAmount;
		
		private string _ShortComment;
		
		private string _SpareField1;
		
		private string _SpareField2;
		
		private string _SpareField3;
		
		private string _SpareField4;
		
		private string _SpareField5;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdvanceIdChanging(int value);
    partial void OnAdvanceIdChanged();
    partial void OnLocalAdvanceIdChanging(System.Nullable<int> value);
    partial void OnLocalAdvanceIdChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnRequestStatusChanging(System.Nullable<short> value);
    partial void OnRequestStatusChanged();
    partial void OnRequestAmountChanging(System.Nullable<decimal> value);
    partial void OnRequestAmountChanged();
    partial void OnRequestTextChanging(string value);
    partial void OnRequestTextChanged();
    partial void OnRequestDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestDateChanged();
    partial void OnApproverIdChanging(System.Nullable<int> value);
    partial void OnApproverIdChanged();
    partial void OnApprovedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnApprovedDateChanged();
    partial void OnProcessedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProcessedDateChanged();
    partial void OnPeriodChanging(System.Nullable<byte> value);
    partial void OnPeriodChanged();
    partial void OnYearChanging(System.Nullable<short> value);
    partial void OnYearChanged();
    partial void OnErrorChanging(bool value);
    partial void OnErrorChanged();
    partial void OnErrorMessageChanging(string value);
    partial void OnErrorMessageChanged();
    partial void OnPortalIdChanging(int value);
    partial void OnPortalIdChanged();
    partial void OnOrigCurrencyChanging(string value);
    partial void OnOrigCurrencyChanged();
    partial void OnOrigCurrencyAmountChanging(System.Nullable<decimal> value);
    partial void OnOrigCurrencyAmountChanged();
    partial void OnShortCommentChanging(string value);
    partial void OnShortCommentChanged();
    partial void OnSpareField1Changing(string value);
    partial void OnSpareField1Changed();
    partial void OnSpareField2Changing(string value);
    partial void OnSpareField2Changed();
    partial void OnSpareField3Changing(string value);
    partial void OnSpareField3Changed();
    partial void OnSpareField4Changing(string value);
    partial void OnSpareField4Changed();
    partial void OnSpareField5Changing(string value);
    partial void OnSpareField5Changed();
    #endregion
		
		public AP_Staff_AdvanceRequest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AdvanceId
		{
			get
			{
				return this._AdvanceId;
			}
			set
			{
				if ((this._AdvanceId != value))
				{
					this.OnAdvanceIdChanging(value);
					this.SendPropertyChanging();
					this._AdvanceId = value;
					this.SendPropertyChanged("AdvanceId");
					this.OnAdvanceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalAdvanceId", DbType="Int")]
		public System.Nullable<int> LocalAdvanceId
		{
			get
			{
				return this._LocalAdvanceId;
			}
			set
			{
				if ((this._LocalAdvanceId != value))
				{
					this.OnLocalAdvanceIdChanging(value);
					this.SendPropertyChanging();
					this._LocalAdvanceId = value;
					this.SendPropertyChanged("LocalAdvanceId");
					this.OnLocalAdvanceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestStatus", DbType="SmallInt")]
		public System.Nullable<short> RequestStatus
		{
			get
			{
				return this._RequestStatus;
			}
			set
			{
				if ((this._RequestStatus != value))
				{
					this.OnRequestStatusChanging(value);
					this.SendPropertyChanging();
					this._RequestStatus = value;
					this.SendPropertyChanged("RequestStatus");
					this.OnRequestStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestAmount", DbType="Money")]
		public System.Nullable<decimal> RequestAmount
		{
			get
			{
				return this._RequestAmount;
			}
			set
			{
				if ((this._RequestAmount != value))
				{
					this.OnRequestAmountChanging(value);
					this.SendPropertyChanging();
					this._RequestAmount = value;
					this.SendPropertyChanged("RequestAmount");
					this.OnRequestAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestText", DbType="NVarChar(MAX)")]
		public string RequestText
		{
			get
			{
				return this._RequestText;
			}
			set
			{
				if ((this._RequestText != value))
				{
					this.OnRequestTextChanging(value);
					this.SendPropertyChanging();
					this._RequestText = value;
					this.SendPropertyChanged("RequestText");
					this.OnRequestTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestDate", DbType="Date")]
		public System.Nullable<System.DateTime> RequestDate
		{
			get
			{
				return this._RequestDate;
			}
			set
			{
				if ((this._RequestDate != value))
				{
					this.OnRequestDateChanging(value);
					this.SendPropertyChanging();
					this._RequestDate = value;
					this.SendPropertyChanged("RequestDate");
					this.OnRequestDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApproverId", DbType="Int")]
		public System.Nullable<int> ApproverId
		{
			get
			{
				return this._ApproverId;
			}
			set
			{
				if ((this._ApproverId != value))
				{
					this.OnApproverIdChanging(value);
					this.SendPropertyChanging();
					this._ApproverId = value;
					this.SendPropertyChanged("ApproverId");
					this.OnApproverIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedDate", DbType="Date")]
		public System.Nullable<System.DateTime> ApprovedDate
		{
			get
			{
				return this._ApprovedDate;
			}
			set
			{
				if ((this._ApprovedDate != value))
				{
					this.OnApprovedDateChanging(value);
					this.SendPropertyChanging();
					this._ApprovedDate = value;
					this.SendPropertyChanged("ApprovedDate");
					this.OnApprovedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessedDate", DbType="Date")]
		public System.Nullable<System.DateTime> ProcessedDate
		{
			get
			{
				return this._ProcessedDate;
			}
			set
			{
				if ((this._ProcessedDate != value))
				{
					this.OnProcessedDateChanging(value);
					this.SendPropertyChanging();
					this._ProcessedDate = value;
					this.SendPropertyChanged("ProcessedDate");
					this.OnProcessedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="TinyInt")]
		public System.Nullable<byte> Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this.OnPeriodChanging(value);
					this.SendPropertyChanging();
					this._Period = value;
					this.SendPropertyChanged("Period");
					this.OnPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="SmallInt")]
		public System.Nullable<short> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Bit NOT NULL")]
		public bool Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(MAX)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this.OnErrorMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessage = value;
					this.SendPropertyChanged("ErrorMessage");
					this.OnErrorMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int NOT NULL")]
		public int PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrigCurrency", DbType="VarChar(5)")]
		public string OrigCurrency
		{
			get
			{
				return this._OrigCurrency;
			}
			set
			{
				if ((this._OrigCurrency != value))
				{
					this.OnOrigCurrencyChanging(value);
					this.SendPropertyChanging();
					this._OrigCurrency = value;
					this.SendPropertyChanged("OrigCurrency");
					this.OnOrigCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrigCurrencyAmount", DbType="Money")]
		public System.Nullable<decimal> OrigCurrencyAmount
		{
			get
			{
				return this._OrigCurrencyAmount;
			}
			set
			{
				if ((this._OrigCurrencyAmount != value))
				{
					this.OnOrigCurrencyAmountChanging(value);
					this.SendPropertyChanging();
					this._OrigCurrencyAmount = value;
					this.SendPropertyChanged("OrigCurrencyAmount");
					this.OnOrigCurrencyAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortComment", DbType="NVarChar(28)")]
		public string ShortComment
		{
			get
			{
				return this._ShortComment;
			}
			set
			{
				if ((this._ShortComment != value))
				{
					this.OnShortCommentChanging(value);
					this.SendPropertyChanging();
					this._ShortComment = value;
					this.SendPropertyChanged("ShortComment");
					this.OnShortCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField1", DbType="NVarChar(50)")]
		public string SpareField1
		{
			get
			{
				return this._SpareField1;
			}
			set
			{
				if ((this._SpareField1 != value))
				{
					this.OnSpareField1Changing(value);
					this.SendPropertyChanging();
					this._SpareField1 = value;
					this.SendPropertyChanged("SpareField1");
					this.OnSpareField1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField2", DbType="NVarChar(50)")]
		public string SpareField2
		{
			get
			{
				return this._SpareField2;
			}
			set
			{
				if ((this._SpareField2 != value))
				{
					this.OnSpareField2Changing(value);
					this.SendPropertyChanging();
					this._SpareField2 = value;
					this.SendPropertyChanged("SpareField2");
					this.OnSpareField2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField3", DbType="NVarChar(50)")]
		public string SpareField3
		{
			get
			{
				return this._SpareField3;
			}
			set
			{
				if ((this._SpareField3 != value))
				{
					this.OnSpareField3Changing(value);
					this.SendPropertyChanging();
					this._SpareField3 = value;
					this.SendPropertyChanged("SpareField3");
					this.OnSpareField3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField4", DbType="NVarChar(50)")]
		public string SpareField4
		{
			get
			{
				return this._SpareField4;
			}
			set
			{
				if ((this._SpareField4 != value))
				{
					this.OnSpareField4Changing(value);
					this.SendPropertyChanging();
					this._SpareField4 = value;
					this.SendPropertyChanged("SpareField4");
					this.OnSpareField4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareField5", DbType="NVarChar(50)")]
		public string SpareField5
		{
			get
			{
				return this._SpareField5;
			}
			set
			{
				if ((this._SpareField5 != value))
				{
					this.OnSpareField5Changing(value);
					this.SendPropertyChanging();
					this._SpareField5 = value;
					this.SendPropertyChanged("SpareField5");
					this.OnSpareField5Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_Staff_Rmb_PerDeimMuliTypes")]
	public partial class AP_Staff_Rmb_PerDeimMuliType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PerDiemTypeId;
		
		private string _Name;
		
		private string _Currency;
		
		private System.Nullable<decimal> _Value;
		
		private System.Nullable<int> _PortalId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPerDiemTypeIdChanging(int value);
    partial void OnPerDiemTypeIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCurrencyChanging(string value);
    partial void OnCurrencyChanged();
    partial void OnValueChanging(System.Nullable<decimal> value);
    partial void OnValueChanged();
    partial void OnPortalIdChanging(System.Nullable<int> value);
    partial void OnPortalIdChanged();
    #endregion
		
		public AP_Staff_Rmb_PerDeimMuliType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerDiemTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PerDiemTypeId
		{
			get
			{
				return this._PerDiemTypeId;
			}
			set
			{
				if ((this._PerDiemTypeId != value))
				{
					this.OnPerDiemTypeIdChanging(value);
					this.SendPropertyChanging();
					this._PerDiemTypeId = value;
					this.SendPropertyChanged("PerDiemTypeId");
					this.OnPerDiemTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="NVarChar(10)")]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this.OnCurrencyChanging(value);
					this.SendPropertyChanging();
					this._Currency = value;
					this.SendPropertyChanged("Currency");
					this.OnCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Money")]
		public System.Nullable<decimal> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalId", DbType="Int")]
		public System.Nullable<int> PortalId
		{
			get
			{
				return this._PortalId;
			}
			set
			{
				if ((this._PortalId != value))
				{
					this.OnPortalIdChanging(value);
					this.SendPropertyChanging();
					this._PortalId = value;
					this.SendPropertyChanged("PortalId");
					this.OnPortalIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AP_Staff_RmbLine")]
	public partial class AP_Staff_RmbLine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _RmbLineNo;
		
		private long _RmbNo;
		
		private short _LineType;
		
		private decimal _GrossAmount;
		
		private System.DateTime _TransDate;
		
		private string _Comment;
		
		private bool _Taxable;
		
		private bool _Receipt;
		
		private bool _VATReceipt;
		
		private System.Nullable<short> _ReceiptNo;
		
		private System.Nullable<short> _Mileage;
		
		private System.Nullable<decimal> _MileageRate;
		
		private string _Spare1;
		
		private string _Spare2;
		
		private string _Spare3;
		
		private string _Spare4;
		
		private string _Spare5;
		
		private string _AnalysisCode;
		
		private bool _Split;
		
		private bool _LargeTransaction;
		
		private bool _OutOfDate;
		
		private bool _Department;
		
		private string _AccountCode;
		
		private string _CostCenter;
		
		private System.Nullable<double> _VATRate;
		
		private string _VATCode;
		
		private System.Nullable<bool> _ForceTaxOrig;
		
		private string _OrigCurrency;
		
		private System.Nullable<decimal> _OrigCurrencyAmount;
		
		private string _ShortComment;
		
		private System.Nullable<byte> _ReceiptMode;
		
		private System.Nullable<int> _ReceiptImageId;
		
		private string _ReceiptText;
		
		private EntityRef<AP_Staff_Rmb> _AP_Staff_Rmb;
		
		private EntityRef<AP_Staff_RmbLineType> _AP_Staff_RmbLineType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRmbLineNoChanging(long value);
    partial void OnRmbLineNoChanged();
    partial void OnRmbNoChanging(long value);
    partial void OnRmbNoChanged();
    partial void OnLineTypeChanging(short value);
    partial void OnLineTypeChanged();
    partial void OnGrossAmountChanging(decimal value);
    partial void OnGrossAmountChanged();
    partial void OnTransDateChanging(System.DateTime value);
    partial void OnTransDateChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnTaxableChanging(bool value);
    partial void OnTaxableChanged();
    partial void OnReceiptChanging(bool value);
    partial void OnReceiptChanged();
    partial void OnVATReceiptChanging(bool value);
    partial void OnVATReceiptChanged();
    partial void OnReceiptNoChanging(System.Nullable<short> value);
    partial void OnReceiptNoChanged();
    partial void OnMileageChanging(System.Nullable<short> value);
    partial void OnMileageChanged();
    partial void OnMileageRateChanging(System.Nullable<decimal> value);
    partial void OnMileageRateChanged();
    partial void OnSpare1Changing(string value);
    partial void OnSpare1Changed();
    partial void OnSpare2Changing(string value);
    partial void OnSpare2Changed();
    partial void OnSpare3Changing(string value);
    partial void OnSpare3Changed();
    partial void OnSpare4Changing(string value);
    partial void OnSpare4Changed();
    partial void OnSpare5Changing(string value);
    partial void OnSpare5Changed();
    partial void OnAnalysisCodeChanging(string value);
    partial void OnAnalysisCodeChanged();
    partial void OnSplitChanging(bool value);
    partial void OnSplitChanged();
    partial void OnLargeTransactionChanging(bool value);
    partial void OnLargeTransactionChanged();
    partial void OnOutOfDateChanging(bool value);
    partial void OnOutOfDateChanged();
    partial void OnDepartmentChanging(bool value);
    partial void OnDepartmentChanged();
    partial void OnAccountCodeChanging(string value);
    partial void OnAccountCodeChanged();
    partial void OnCostCenterChanging(string value);
    partial void OnCostCenterChanged();
    partial void OnVATRateChanging(System.Nullable<double> value);
    partial void OnVATRateChanged();
    partial void OnVATCodeChanging(string value);
    partial void OnVATCodeChanged();
    partial void OnForceTaxOrigChanging(System.Nullable<bool> value);
    partial void OnForceTaxOrigChanged();
    partial void OnOrigCurrencyChanging(string value);
    partial void OnOrigCurrencyChanged();
    partial void OnOrigCurrencyAmountChanging(System.Nullable<decimal> value);
    partial void OnOrigCurrencyAmountChanged();
    partial void OnShortCommentChanging(string value);
    partial void OnShortCommentChanged();
    partial void OnReceiptModeChanging(System.Nullable<byte> value);
    partial void OnReceiptModeChanged();
    partial void OnReceiptImageIdChanging(System.Nullable<int> value);
    partial void OnReceiptImageIdChanged();
    partial void OnReceiptTextChanging(string value);
    partial void OnReceiptTextChanged();
    #endregion
		
		public AP_Staff_RmbLine()
		{
			this._AP_Staff_Rmb = default(EntityRef<AP_Staff_Rmb>);
			this._AP_Staff_RmbLineType = default(EntityRef<AP_Staff_RmbLineType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RmbLineNo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long RmbLineNo
		{
			get
			{
				return this._RmbLineNo;
			}
			set
			{
				if ((this._RmbLineNo != value))
				{
					this.OnRmbLineNoChanging(value);
					this.SendPropertyChanging();
					this._RmbLineNo = value;
					this.SendPropertyChanged("RmbLineNo");
					this.OnRmbLineNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RmbNo", DbType="BigInt NOT NULL")]
		public long RmbNo
		{
			get
			{
				return this._RmbNo;
			}
			set
			{
				if ((this._RmbNo != value))
				{
					if (this._AP_Staff_Rmb.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRmbNoChanging(value);
					this.SendPropertyChanging();
					this._RmbNo = value;
					this.SendPropertyChanged("RmbNo");
					this.OnRmbNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineType", DbType="SmallInt NOT NULL")]
		public short LineType
		{
			get
			{
				return this._LineType;
			}
			set
			{
				if ((this._LineType != value))
				{
					if (this._AP_Staff_RmbLineType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLineTypeChanging(value);
					this.SendPropertyChanging();
					this._LineType = value;
					this.SendPropertyChanged("LineType");
					this.OnLineTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrossAmount", DbType="Money NOT NULL")]
		public decimal GrossAmount
		{
			get
			{
				return this._GrossAmount;
			}
			set
			{
				if ((this._GrossAmount != value))
				{
					this.OnGrossAmountChanging(value);
					this.SendPropertyChanging();
					this._GrossAmount = value;
					this.SendPropertyChanged("GrossAmount");
					this.OnGrossAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransDate", DbType="Date NOT NULL")]
		public System.DateTime TransDate
		{
			get
			{
				return this._TransDate;
			}
			set
			{
				if ((this._TransDate != value))
				{
					this.OnTransDateChanging(value);
					this.SendPropertyChanging();
					this._TransDate = value;
					this.SendPropertyChanged("TransDate");
					this.OnTransDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taxable", DbType="Bit NOT NULL")]
		public bool Taxable
		{
			get
			{
				return this._Taxable;
			}
			set
			{
				if ((this._Taxable != value))
				{
					this.OnTaxableChanging(value);
					this.SendPropertyChanging();
					this._Taxable = value;
					this.SendPropertyChanged("Taxable");
					this.OnTaxableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receipt", DbType="Bit NOT NULL")]
		public bool Receipt
		{
			get
			{
				return this._Receipt;
			}
			set
			{
				if ((this._Receipt != value))
				{
					this.OnReceiptChanging(value);
					this.SendPropertyChanging();
					this._Receipt = value;
					this.SendPropertyChanged("Receipt");
					this.OnReceiptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATReceipt", DbType="Bit NOT NULL")]
		public bool VATReceipt
		{
			get
			{
				return this._VATReceipt;
			}
			set
			{
				if ((this._VATReceipt != value))
				{
					this.OnVATReceiptChanging(value);
					this.SendPropertyChanging();
					this._VATReceipt = value;
					this.SendPropertyChanged("VATReceipt");
					this.OnVATReceiptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptNo", DbType="SmallInt")]
		public System.Nullable<short> ReceiptNo
		{
			get
			{
				return this._ReceiptNo;
			}
			set
			{
				if ((this._ReceiptNo != value))
				{
					this.OnReceiptNoChanging(value);
					this.SendPropertyChanging();
					this._ReceiptNo = value;
					this.SendPropertyChanged("ReceiptNo");
					this.OnReceiptNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mileage", DbType="SmallInt")]
		public System.Nullable<short> Mileage
		{
			get
			{
				return this._Mileage;
			}
			set
			{
				if ((this._Mileage != value))
				{
					this.OnMileageChanging(value);
					this.SendPropertyChanging();
					this._Mileage = value;
					this.SendPropertyChanged("Mileage");
					this.OnMileageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MileageRate", DbType="Money")]
		public System.Nullable<decimal> MileageRate
		{
			get
			{
				return this._MileageRate;
			}
			set
			{
				if ((this._MileageRate != value))
				{
					this.OnMileageRateChanging(value);
					this.SendPropertyChanging();
					this._MileageRate = value;
					this.SendPropertyChanged("MileageRate");
					this.OnMileageRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spare1", DbType="NVarChar(MAX)")]
		public string Spare1
		{
			get
			{
				return this._Spare1;
			}
			set
			{
				if ((this._Spare1 != value))
				{
					this.OnSpare1Changing(value);
					this.SendPropertyChanging();
					this._Spare1 = value;
					this.SendPropertyChanged("Spare1");
					this.OnSpare1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spare2", DbType="NVarChar(MAX)")]
		public string Spare2
		{
			get
			{
				return this._Spare2;
			}
			set
			{
				if ((this._Spare2 != value))
				{
					this.OnSpare2Changing(value);
					this.SendPropertyChanging();
					this._Spare2 = value;
					this.SendPropertyChanged("Spare2");
					this.OnSpare2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spare3", DbType="NVarChar(100)")]
		public string Spare3
		{
			get
			{
				return this._Spare3;
			}
			set
			{
				if ((this._Spare3 != value))
				{
					this.OnSpare3Changing(value);
					this.SendPropertyChanging();
					this._Spare3 = value;
					this.SendPropertyChanged("Spare3");
					this.OnSpare3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spare4", DbType="NVarChar(100)")]
		public string Spare4
		{
			get
			{
				return this._Spare4;
			}
			set
			{
				if ((this._Spare4 != value))
				{
					this.OnSpare4Changing(value);
					this.SendPropertyChanging();
					this._Spare4 = value;
					this.SendPropertyChanged("Spare4");
					this.OnSpare4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spare5", DbType="NVarChar(100)")]
		public string Spare5
		{
			get
			{
				return this._Spare5;
			}
			set
			{
				if ((this._Spare5 != value))
				{
					this.OnSpare5Changing(value);
					this.SendPropertyChanging();
					this._Spare5 = value;
					this.SendPropertyChanged("Spare5");
					this.OnSpare5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnalysisCode", DbType="NVarChar(50)")]
		public string AnalysisCode
		{
			get
			{
				return this._AnalysisCode;
			}
			set
			{
				if ((this._AnalysisCode != value))
				{
					this.OnAnalysisCodeChanging(value);
					this.SendPropertyChanging();
					this._AnalysisCode = value;
					this.SendPropertyChanged("AnalysisCode");
					this.OnAnalysisCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Split", DbType="Bit NOT NULL")]
		public bool Split
		{
			get
			{
				return this._Split;
			}
			set
			{
				if ((this._Split != value))
				{
					this.OnSplitChanging(value);
					this.SendPropertyChanging();
					this._Split = value;
					this.SendPropertyChanged("Split");
					this.OnSplitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargeTransaction", DbType="Bit NOT NULL")]
		public bool LargeTransaction
		{
			get
			{
				return this._LargeTransaction;
			}
			set
			{
				if ((this._LargeTransaction != value))
				{
					this.OnLargeTransactionChanging(value);
					this.SendPropertyChanging();
					this._LargeTransaction = value;
					this.SendPropertyChanged("LargeTransaction");
					this.OnLargeTransactionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutOfDate", DbType="Bit NOT NULL")]
		public bool OutOfDate
		{
			get
			{
				return this._OutOfDate;
			}
			set
			{
				if ((this._OutOfDate != value))
				{
					this.OnOutOfDateChanging(value);
					this.SendPropertyChanging();
					this._OutOfDate = value;
					this.SendPropertyChanged("OutOfDate");
					this.OnOutOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Bit NOT NULL")]
		public bool Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(12)")]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this.OnAccountCodeChanging(value);
					this.SendPropertyChanging();
					this._AccountCode = value;
					this.SendPropertyChanged("AccountCode");
					this.OnAccountCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCenter", DbType="NVarChar(12)")]
		public string CostCenter
		{
			get
			{
				return this._CostCenter;
			}
			set
			{
				if ((this._CostCenter != value))
				{
					this.OnCostCenterChanging(value);
					this.SendPropertyChanging();
					this._CostCenter = value;
					this.SendPropertyChanged("CostCenter");
					this.OnCostCenterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATRate", DbType="Float")]
		public System.Nullable<double> VATRate
		{
			get
			{
				return this._VATRate;
			}
			set
			{
				if ((this._VATRate != value))
				{
					this.OnVATRateChanging(value);
					this.SendPropertyChanging();
					this._VATRate = value;
					this.SendPropertyChanged("VATRate");
					this.OnVATRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATCode", DbType="NVarChar(8)")]
		public string VATCode
		{
			get
			{
				return this._VATCode;
			}
			set
			{
				if ((this._VATCode != value))
				{
					this.OnVATCodeChanging(value);
					this.SendPropertyChanging();
					this._VATCode = value;
					this.SendPropertyChanged("VATCode");
					this.OnVATCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForceTaxOrig", DbType="Bit")]
		public System.Nullable<bool> ForceTaxOrig
		{
			get
			{
				return this._ForceTaxOrig;
			}
			set
			{
				if ((this._ForceTaxOrig != value))
				{
					this.OnForceTaxOrigChanging(value);
					this.SendPropertyChanging();
					this._ForceTaxOrig = value;
					this.SendPropertyChanged("ForceTaxOrig");
					this.OnForceTaxOrigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrigCurrency", DbType="VarChar(5)")]
		public string OrigCurrency
		{
			get
			{
				return this._OrigCurrency;
			}
			set
			{
				if ((this._OrigCurrency != value))
				{
					this.OnOrigCurrencyChanging(value);
					this.SendPropertyChanging();
					this._OrigCurrency = value;
					this.SendPropertyChanged("OrigCurrency");
					this.OnOrigCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrigCurrencyAmount", DbType="Money")]
		public System.Nullable<decimal> OrigCurrencyAmount
		{
			get
			{
				return this._OrigCurrencyAmount;
			}
			set
			{
				if ((this._OrigCurrencyAmount != value))
				{
					this.OnOrigCurrencyAmountChanging(value);
					this.SendPropertyChanging();
					this._OrigCurrencyAmount = value;
					this.SendPropertyChanged("OrigCurrencyAmount");
					this.OnOrigCurrencyAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortComment", DbType="NVarChar(28)")]
		public string ShortComment
		{
			get
			{
				return this._ShortComment;
			}
			set
			{
				if ((this._ShortComment != value))
				{
					this.OnShortCommentChanging(value);
					this.SendPropertyChanging();
					this._ShortComment = value;
					this.SendPropertyChanged("ShortComment");
					this.OnShortCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptMode", DbType="TinyInt")]
		public System.Nullable<byte> ReceiptMode
		{
			get
			{
				return this._ReceiptMode;
			}
			set
			{
				if ((this._ReceiptMode != value))
				{
					this.OnReceiptModeChanging(value);
					this.SendPropertyChanging();
					this._ReceiptMode = value;
					this.SendPropertyChanged("ReceiptMode");
					this.OnReceiptModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptImageId", DbType="Int")]
		public System.Nullable<int> ReceiptImageId
		{
			get
			{
				return this._ReceiptImageId;
			}
			set
			{
				if ((this._ReceiptImageId != value))
				{
					this.OnReceiptImageIdChanging(value);
					this.SendPropertyChanging();
					this._ReceiptImageId = value;
					this.SendPropertyChanged("ReceiptImageId");
					this.OnReceiptImageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptText", DbType="NVarChar(MAX)")]
		public string ReceiptText
		{
			get
			{
				return this._ReceiptText;
			}
			set
			{
				if ((this._ReceiptText != value))
				{
					this.OnReceiptTextChanging(value);
					this.SendPropertyChanging();
					this._ReceiptText = value;
					this.SendPropertyChanged("ReceiptText");
					this.OnReceiptTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AP_Staff_Rmb_AP_Staff_RmbLine", Storage="_AP_Staff_Rmb", ThisKey="RmbNo", OtherKey="RMBNo", IsForeignKey=true)]
		public AP_Staff_Rmb AP_Staff_Rmb
		{
			get
			{
				return this._AP_Staff_Rmb.Entity;
			}
			set
			{
				AP_Staff_Rmb previousValue = this._AP_Staff_Rmb.Entity;
				if (((previousValue != value) 
							|| (this._AP_Staff_Rmb.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AP_Staff_Rmb.Entity = null;
						previousValue.AP_Staff_RmbLines.Remove(this);
					}
					this._AP_Staff_Rmb.Entity = value;
					if ((value != null))
					{
						value.AP_Staff_RmbLines.Add(this);
						this._RmbNo = value.RMBNo;
					}
					else
					{
						this._RmbNo = default(long);
					}
					this.SendPropertyChanged("AP_Staff_Rmb");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AP_Staff_RmbLineType_AP_Staff_RmbLine", Storage="_AP_Staff_RmbLineType", ThisKey="LineType", OtherKey="LineTypeId", IsForeignKey=true)]
		public AP_Staff_RmbLineType AP_Staff_RmbLineType
		{
			get
			{
				return this._AP_Staff_RmbLineType.Entity;
			}
			set
			{
				AP_Staff_RmbLineType previousValue = this._AP_Staff_RmbLineType.Entity;
				if (((previousValue != value) 
							|| (this._AP_Staff_RmbLineType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AP_Staff_RmbLineType.Entity = null;
						previousValue.AP_Staff_RmbLines.Remove(this);
					}
					this._AP_Staff_RmbLineType.Entity = value;
					if ((value != null))
					{
						value.AP_Staff_RmbLines.Add(this);
						this._LineType = value.LineTypeId;
					}
					else
					{
						this._LineType = default(short);
					}
					this.SendPropertyChanged("AP_Staff_RmbLineType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
